main: me.serbinskis.smptweaks.Main
name: SMPTweaks
api-version: 1.13
version: 1.0
load: STARTUP
author: Serbinskis
softdepend: [ ProtocolLib, PlaceholderAPI ]

commands:
  SMPTweaks:
    description: Tweak some settings!
    usage: "Usage: /<command> <tweak> <setting>"